### ISSUE TITLE
Mattermost v4 support

### ISSUE THREAD

**Issue by jostyee** [cronn-de/mattermost-themes-cronn#1]
This is a nice theme, but cannot be imported directly in Mattermost 4.0, can you please update it again?

**Comment by ldziedziul** [comment]
Hi @jostyee, many thanks for your report! Mattermost 4.x has migrated from the CSV format to a more human readable JSON. We didn't notice that because of the silent conversion of our current settings during the upgrade to the Mattermost 4.0.

I've updated description with JSON themes so it should work you as well.

**Comment by jostyee** [comment]
@ldziedziul Thanks, it's working now.
